-- =========================================================
-- TRANSPORTATION PENALTY TRACKER
-- Run this entire script in the Supabase SQL Editor.
-- =========================================================

create extension if not exists pgcrypto;

-- -------------------------
-- Schools
-- -------------------------
create table if not exists public.schools (
  id bigint generated by default as identity primary key,
  school_name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- The list can be edited at any time in Supabase.
insert into public.schools (school_name) values
('Aerospace/Hydrospace Engineering and Physical Sciences'),
('Aquaculture Science and Technology Education Center'),
('Barnum School'),
('Batalla School'),
('Beardsley School'),
('Black Rock School'),
('Blackham School'),
('Bridgeport Learning Center'),
('Bridgeport Military Academy'),
('Bryant School'),
('Central High School'),
('Classical Studies Academy'),
('Claytor School'),
('Columbus School'),
('Curiale School'),
('Discovery Magnet School'),
('Dunbar School'),
('Edison School'),
('Fairchild Wheeler Interdistrict Magnet Campus'),
('Geraldine Johnson School'),
('Hall School'),
('Hallen School'),
('Harding High School'),
('High Horizons Magnet School'),
('Information Technology and Software Engineering High School'),
('Interdistrict Discovery Magnet School'),
('Jettie S. Tisdale School'),
('John Winthrop School'),
('Madison School'),
('Marin School'),
('Multicultural Magnet School'),
('Park City Magnet School'),
('Read School'),
('Roosevelt School'),
('Skane Center'),
('Thomas Hooker School'),
('Waltersville School'),
('Wilbur Cross School')
on conflict (school_name) do nothing;

-- -------------------------
-- Profiles
-- -------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  role text not null default 'user' check (role in ('admin', 'user')),
  school_id bigint references public.schools(id),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Automatically create a basic profile when a new Authentication user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    'user'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- -------------------------
-- Late bus entries
-- -------------------------
create table if not exists public.late_bus_entries (
  id uuid primary key default gen_random_uuid(),
  incident_date date not null,
  school_id bigint not null references public.schools(id),
  bus_number text not null,
  route_number text,
  scheduled_time time not null,
  actual_time time not null,
  minutes_late integer not null check (minutes_late > 0),
  reason text,
  notes text not null check (length(trim(notes)) > 0),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists late_bus_duplicate_guard
on public.late_bus_entries (
  incident_date,
  school_id,
  lower(bus_number),
  scheduled_time
);

create index if not exists late_bus_entries_month_idx
on public.late_bus_entries (incident_date);

create index if not exists late_bus_entries_created_by_idx
on public.late_bus_entries (created_by);

create index if not exists late_bus_entries_school_idx
on public.late_bus_entries (school_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_late_bus_updated_at on public.late_bus_entries;
create trigger set_late_bus_updated_at
before update on public.late_bus_entries
for each row execute function public.set_updated_at();

-- -------------------------
-- Security helper
-- -------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and active = true
  );
$$;

grant execute on function public.is_admin() to authenticated;

-- -------------------------
-- RLS
-- -------------------------
alter table public.schools enable row level security;
alter table public.profiles enable row level security;
alter table public.late_bus_entries enable row level security;

drop policy if exists "Authenticated users read schools" on public.schools;
create policy "Authenticated users read schools"
on public.schools for select
to authenticated
using (true);

drop policy if exists "Users read own profile admins read all" on public.profiles;
create policy "Users read own profile admins read all"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "Admins update profiles" on public.profiles;
create policy "Admins update profiles"
on public.profiles for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Users insert own entries" on public.late_bus_entries;
create policy "Users insert own entries"
on public.late_bus_entries for insert
to authenticated
with check (
  created_by = auth.uid()
  and (
    public.is_admin()
    or school_id = (select school_id from public.profiles where id = auth.uid())
  )
);

drop policy if exists "Users read own entries admins read all" on public.late_bus_entries;
create policy "Users read own entries admins read all"
on public.late_bus_entries for select
to authenticated
using (created_by = auth.uid() or public.is_admin());

drop policy if exists "Users update own entries admins update all" on public.late_bus_entries;
create policy "Users update own entries admins update all"
on public.late_bus_entries for update
to authenticated
using (created_by = auth.uid() or public.is_admin())
with check (
  created_by = auth.uid() or public.is_admin()
);

drop policy if exists "Users delete own entries admins delete all" on public.late_bus_entries;
create policy "Users delete own entries admins delete all"
on public.late_bus_entries for delete
to authenticated
using (created_by = auth.uid() or public.is_admin());

-- -------------------------
-- Monthly billing view
-- First two incidents are not billed.
-- Every incident beginning with incident #3 is $50.
-- -------------------------
create or replace view public.monthly_penalty_summary
with (security_invoker = true)
as
select
  date_trunc('month', incident_date)::date as penalty_month,
  count(*)::integer as total_late_incidents,
  least(count(*), 2)::integer as non_billable_incidents,
  greatest(count(*) - 2, 0)::integer as billable_incidents,
  greatest(count(*) - 2, 0) * 50.00 as amount_due
from public.late_bus_entries
group by date_trunc('month', incident_date);

grant select on public.monthly_penalty_summary to authenticated;

-- =========================================================
-- AFTER CREATING YOUR USERS IN AUTHENTICATION
-- Use statements like these to assign roles and schools.
-- =========================================================

-- Make PJ an administrator:
-- update public.profiles
-- set role = 'admin', full_name = 'PJ Karaffa'
-- where email = 'pkaraffa@bridgeportedu.net';

-- Assign a school user:
-- update public.profiles
-- set role = 'user',
--     full_name = 'Employee Name',
--     school_id = (select id from public.schools where school_name = 'Barnum School')
-- where email = 'employee@bridgeportedu.net';

-- Check the monthly penalty:
-- select * from public.monthly_penalty_summary order by penalty_month desc;
